### ISSUE TITLE
403 Forbidden worker不可用？

### ISSUE THREAD

**Issue by appotry** [SukkaW/cloudflare-workers-async-google-analytics#13]
```
403 Forbidden
content-length:13
content-type:text/html
```

安装readme设置后，报错
是个人设置问题，还是现在这个方法不可用了？

**Comment by appotry** [comment]
可能是本地浏览的原因？

部署到服务器上，但是统计数据超时，

**Comment by appotry** [comment]
没有什么问题，还可用。是域名限制原因，不能本地测试，也不能用其它域名测试

**Comment by homuraLan** [comment]
具体怎么弄能说下不
![image](https://github.com/SukkaW/cloudflare-workers-async-google-analytics/assets/96775034/e0085e9e-2781-403e-9ea4-a2de04ee93c2)
