### ISSUE TITLE
提交的数据为中文时，脚本无法正常工作

### ISSUE THREAD

**Issue by Oxygen233** [SukkaW/cloudflare-workers-async-google-analytics#4]
比如标题为中文时，GA后台显示乱码
![Snipaste_2020-02-15_13-40-19](https://user-images.githubusercontent.com/61075067/74582558-c1cad280-4ff8-11ea-88bd-90c822d6bbca.png)

**Comment by EtaoinWu** [comment]
复现同一问题。Close 了这一 issue 是因为解决了吗？

**Comment by SukkaW** [comment]
@EtaoinWu 没有解决。

我 reopen 吧。

**Comment by SukkaW** [comment]
Fixed.
