### ISSUE TITLE
Pageview event in an SPA

### ISSUE THREAD

**Issue by winstef** [SukkaW/cloudflare-workers-async-google-analytics#6]
Hi,

Is it possible to use your code in a single page application (NextJS) and send an event (e.g: ga('send', 'pageview') )  whenever a new page is loaded so we can track pages as well?

thanks

**Comment by SukkaW** [comment]
Maybe expose a function to the global could achieve this.

**Comment by SukkaW** [comment]
Done in https://github.com/SukkaW/cloudflare-workers-async-google-analytics/commit/4e6ac6956ff3a70973f56159a8b4e16a0c6a01f1 and launched in `cfga@1.0.3`.

[1.0.3 Release Notes](https://github.com/SukkaW/cloudflare-workers-async-google-analytics/releases/tag/1.0.3).

**Comment by winstef** [comment]
thanks, works great!
